default_platform :ios

lane :gen do
  generate_project
  generate_assets
  skip_docs
  open_project
end

lane :generate_project do |options|
  generate_module(name: "App")
end

lane :generate_assets do 
  Dir.chdir("..") do
    sh "cd App; swiftgen"
  end
end

lane :generate_module do |values|
  name = values[:name]
  Dir.chdir("..") do
    sh 'xcodegen -p ' + name + '/ -s ' + name + '/project.yml'
  end
end

lane :open_project do
  Dir.chdir("..") do
    sh "cd App; open App.xcodeproj"
  end
end

lane :build_project do
  build_ios_app(
    project: "./App/App.xcodeproj",
    scheme: "App",
    buildlog_path: "./App/output",
    build_path: "./App/output",
    skip_archive: true,
    skip_codesigning: true
  )
end

lane :run_xcov do
  clear_xcov_output
  xcov(
    project: "./App/App.xcodeproj",
    scheme: "AppTests",
    output_directory: "./App/xcov_output",
    include_targets: "WeatherPlaypen.package",
    skip_slack: true,
  )
end

lane :clear_xcov_output do
   sh "cd .. && if [ -d 'xcov_output' ]; then rm -Rf xcov_output; fi"
end
